services:
  postgres:
    container_name: bhs-site-app-bd
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:latest
    networks:
      - bhs-site-app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prisma:
    container_name: bhs-site-app-prisma
    build:
      context: .
      dockerfile: Dockerfile
    command: npx prisma migrate deploy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - bhs-site-app-network
    volumes:
      - .:/app
    restart: on-failure

networks:
  bhs-site-app-network:
    driver: bridge

volumes:
  postgres_data:
    name: bhs-site-app_postgres_data
