version: "3.3" # Versão compatível com Docker Compose 1.25.0+

services:
  postgres:
    image: postgres:latest
    container_name: bhs-site-app-bd
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bhs-site-app-network

volumes:
  postgres_data:

networks:
  bhs-site-app-network:
    driver: bridge
