name: Azure Static Web Apps CI/CD - Next.js 15

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Recomendado para Next.js 15
          cache: "npm"

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_PUBLIC_VERCEL_ENV: production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "." # Raiz do projeto
          output_location: ".next" # Pasta de build do Next.js 15
          skip_app_build: true # Já fizemos o build no passo anterior
          is_static_export: false # Para SSR/ISR
